# Generated by Django 5.2.14 on 2026-05-11 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('web', 'Web'), ('outbound', 'Outbound PSTN')], default='web', max_length=20)),
                ('vapi_call_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in_progress', 'In progress'), ('ended', 'Ended'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('customer_number', models.CharField(blank=True, default='', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='studio.call')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotionIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('data_source_id', models.CharField(max_length=64)),
                ('database_id', models.CharField(max_length=64)),
                ('field_mappings', models.JSONField(blank=True, default=list)),
                ('token_ciphertext', models.BinaryField()),
                ('vapi_tools', models.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notion_integrations', to='accounts.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('global_prompt', models.TextField(blank=True, default='')),
                ('graph', models.JSONField(blank=True, default=dict)),
                ('vapi_workflow_id', models.CharField(blank=True, default='', max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='accounts.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('vapi_assistant_id', models.CharField(blank=True, default='', max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='accounts.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization', 'updated_at'], name='studio_agen_organiz_149b8d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['organization', 'created_at'], name='studio_call_organiz_328728_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['vapi_call_id'], name='studio_call_vapi_ca_2d1b01_idx'),
        ),
        migrations.AddIndex(
            model_name='callevent',
            index=models.Index(fields=['call', 'created_at'], name='studio_call_call_id_61ad16_idx'),
        ),
        migrations.AddIndex(
            model_name='notionintegration',
            index=models.Index(fields=['organization', 'updated_at'], name='studio_noti_organiz_707f16_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'updated_at'], name='studio_work_organiz_b4d266_idx'),
        ),
    ]
