# Generated by Django 5.2.14 on 2026-07-02 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('studio', '0003_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('target_kind', models.CharField(choices=[('agent', 'Agent'), ('squad', 'Squad')], max_length=16)),
                ('target_ext_id', models.CharField(blank=True, default='', max_length=32)),
                ('vapi_target_id', models.CharField(blank=True, default='', max_length=64)),
                ('vapi_phone_number_id', models.CharField(blank=True, default='', max_length=64)),
                ('customers', models.JSONField(blank=True, default=list)),
                ('schedule_earliest_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='scheduled', max_length=32)),
                ('vapi_campaign_id', models.CharField(blank=True, default='', max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.organization')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='studio.phonenumber')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='studio_camp_organiz_437dfd_idx')],
            },
        ),
    ]
